---
- name: Ensure EPEL repo is installed
  include: epel.yml

- name: Update all packages and reboot
  include: update.yml

- name: Ensure required packages are installed
  include: yum.yml

- name: Ensure Docker is properly installed
  include: docker.yml

- name: Ensure /etc/origin/node exists
  file:
    path: /etc/origin/node
    state: directory
    recurse: yes

- name: Ensure /etc/origin/node/resolv.conf exists
  file:
    path: /etc/origin/node/resolv.conf
    state: touch
