---
- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: "epel"
  register: update_system

- name: Reboot if state changed
  shell: sleep 2 && shutdown -r now 'System update reboot'
  async: 1
  poll: 0
  ignore_errors: true
  when: update_system.changed

- name: Waiting for hosts to be available
  wait_for:
    host: '{{ item }}'
    port: 22
    state: started
    delay: 10
    timeout: 45
  with_items: '{{ play_hosts }}'
  connection: local
  when: update_system.changed
